use datawarehouse

select * from gold.dim_customers

select distinct
DATEDIFF(year,birthdate,GETDATE()) as age
from gold.dim_customers

select distinct
avg(DATEDIFF(year,birthdate,GETDATE())) as age
from gold.dim_customers

--- Explore all objects in the database
select * from INFORMATION_SCHEMA.TABLES

--- Explore all columns is the database
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'fact_sales'

-- Explore all countries our customers comes from
select distinct country from gold.dim_customers

--Explore all categories
select distinct category ,subcategory,product_name from gold.dim_products
order by 1,2,3

--Date Exploration
--Find the date of first and last order

select min(order_date) as first_order_date,
max(order_date) as last_order_date
from gold.fact_sales

--How many years of sales available
select 
MIN(order_date) as first_orderdate, MAX(order_date) as last_order_date,
DATEDIFF(YEAR,min(order_date),MAX(order_date)) as order_range_years
from gold.fact_sales

---Find the youngest and oldest customers
select 
MIN(birthdate) as oldest_birthdate,
DATEDIFF(year,min(birthdate),GETDATE()) as oldest_age,
MAX(birthdate) as youngest_birthdate,
DATEDIFF(YEAR,MAX(birthdate),getdate()) as youngest_age
from gold.dim_customers

select * from gold.fact_sales
--Find the total sales
select concat(round(SUM(sales)/1000000,0),'M') as total_sales
from gold.fact_sales

--find how many itemd are sold
select sum(quantity)as Total_items_sold from gold.fact_sales

--find the average seling price
select AVG(price) as Avg_Selling_price from gold.fact_sales

select * from gold.dim_products
--find the total number of products
select COUNT(prduct_id) as Total_Products FROM gold.dim_products

--fild the total number of orders
select COUNT(distinct order_number)as Total_Orders FROM gold.fact_sales

select * from gold.dim_customers
--find the total number of customers
select COUNT(customer_id) as Total_Customers from gold.dim_customers

--find the total number of customers that has placed an order
select COUNT( distinct customer_key) as Total_customers from gold.fact_sales

--Generate a report that shows all key metric of business

select 'Total Sales' as Measure_Name,SUM(sales)as Measure_value from gold.fact_sales
union all	
select 'Total Quantity' ,sum(quantity) from gold.fact_sales
union all
select 'Average Price',AVG(price) as Avg_Selling_price from gold.fact_sales
union all
select 'Total Customers' ,COUNT(customer_id) from gold.dim_customers
union all
select 'Total Products',COUNT(prduct_id) as Total_Products FROM gold.dim_products
union all
select 'Total Orders',COUNT(distinct order_number)as Total_Orders FROM gold.fact_sales

---Magnitude

--Find Total Customer by countries
select country,
COUNT(customer_key) as Total_Customer
from gold.dim_customers
group by country
order by Total_Customer desc

--Find total customer by gender
select gender,
COUNT(customer_key) as Total_Customer
from gold.dim_customers
group by gender
order by Total_Customer desc

--Find total products by category
select category,
COUNT(product_key) as Total_Product
from gold.dim_products
group by category
order by Total_Product desc

-- What is the average cost of each category
select category,
AVG(cost)AS Average_Cost
from gold.dim_products
group by category
order by Average_Cost desc

--What is the total revenue generated for each category
select 
p.category,
sum(f.sales) as Total_Revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by category
order by Total_Revenue desc


--Find total revenue generated by each customer
select 
c.customer_key,
c.fist_name,
c.last_name,
SUM(f.sales) as Total_Revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key,fist_name,last_name	
order by Total_Revenue desc

--What is the distribution of sold items across countries
select 
c.country,
SUM(f.quantity) as Sold_Items
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by country
order by Sold_Items desc

--Ranking
--Which 5 products generated highest revenue
select top 5
p.product_name,
SUM(f.sales) as Revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by product_name
order by Revenue desc

--By Window Function
select *
from(
	select
	p.product_name,
	SUM(f.sales) as Revenue,
	row_number()over(order by SUM(f.sales) desc) as rank_products
	from gold.fact_sales f
	left join gold.dim_products p
	on f.product_key=p.product_key
	group by product_name
	)t
where rank_Products <=5


--What are the 5 worst performing products in terms of sales
select top 5
p.product_name,
SUM(f.sales) as Revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by product_name
order by Revenue

select top 2
p.category,
SUM(f.sales) as Revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by category
order by Revenue 

--Which 5 countries generated highest revenue
select top 5
c.country,
SUM(f.sales) as Revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by country
order by Revenue desc

--What are the 5 worst performing customers in terms of orders
select top 5
c.fist_name,
c.last_name,
COUNT(f.quantity) as Orders
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.fist_name,c.last_name
order by Orders 

--Find The top 10 customers who have generated the highest revenue 
select top 10
c.fist_name,
c.last_name,
SUM(f.sales) as Revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.fist_name,c.last_name
order by Revenue desc

-- the 3 customers with the fewest order placed
select top 3
c.customer_key,
c.fist_name,
c.last_name,
COUNT(distinct f.order_number) as Orders
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by
c.customer_key,
c.fist_name,
c.last_name
order by Orders 